FROM nginx:stable

COPY index.html /usr/share/nginx/html/index.html 
COPY style.css /usr/share/nginx/html/style.css
COPY javascript.js /usr/share/nginx/html/javascript.js

COPY . /usr/share/nginx/html/

EXPOSE 80
